version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
